// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rnvnngddhyxrsthkasnw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJudm5uZ2RkaHl4cnN0aGthc253Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzMjA3NjYsImV4cCI6MjA1OTg5Njc2Nn0.BsEWDFdbMC5SS3poD0SBsobOLgQ32SE7o_oOECvEBow";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);